name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Mosquitto MQTT Broker in GitHub Actions
      uses: Namoshek/mosquitto-github-action@v1

    - name: Build
      run: go build -v ./...

    - name: Run mosquitto
      run: mosquitto -p 1883 -d

    - name: Test
      run: go test -v ./...
